name: lsnew
channels:
  - defaults
  - conda-forge
dependencies:
  - arcsi=3.2.4=py37_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.4=pyh9f0ad1d_0
  - boost-cpp=1.70.0=h6a4c333_2
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cfitsio=3.470=hfa6e2cd_2
  - cgal-cpp=5.0.1=h411bc12_0
  - colorama=0.4.3=py_0
  - curl=7.68.0=h4496350_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - eigen=3.3.7=he980bc4_1001
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he025d50_2
  - freetype=2.10.1=ha9979f8_0
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.0.2=py37h2fee047_4
  - geos=3.7.2=he025d50_2
  - geotiff=1.5.1=h765a46f_7
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py37hc0c2ac7_1002
  - gsl=2.5=h631dd0c_1
  - h5py=2.10.0=nompi_py37h422b98e_102
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - importlib-metadata=1.6.0=py37hc8dfbb8_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.0=166
  - ipykernel=5.2.0=py37h5ca1d4c_1
  - ipython=7.13.0=py37hc8dfbb8_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py37hc8dfbb8_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.2=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kealib=1.4.13=hd6dc3df_0
  - kiwisolver=1.2.0=py37heaa310e_0
  - krb5=1.16.4=hdd46e55_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.68.0=h4496350_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.2=h4a92af1_4
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h4ece8bf_1010
  - liblapack=3.8.0=15_mkl
  - libnetcdf=4.7.1=nompi_he2c6080_102
  - libpng=1.6.37=hfe6a214_1
  - libpq=11.5=hb0bdaea_2
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialite=4.3.0a=h2b2ca8d_1032
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h885aae3_6
  - libwebp=1.0.2=hfa6e2cd_5
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py37h8055547_1
  - matplotlib-base=3.2.1=py37h911224e_0
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - mpfr=4.0.2=h2fa13f4_0
  - mpir=3.0.0=he025d50_1002
  - msys2-conda-epoch=20160418=1
  - muparser=2.2.6.1=he025d50_1
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h90d3380_1
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1f=hfa6e2cd_0
  - pandas=1.0.3=py37h9b59f54_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - pcre=8.44=h6538335_0
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py_2
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h06f7779_2
  - proj=6.2.1=ha7a8c7b_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - py6s=1.7.2=py_2
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1001
  - pyrsistent=0.16.0=py37h8055547_0
  - pysolar=0.6=py_0
  - python=3.7.6=h60c2a47_5_cpython
  - python-dateutil=2.8.1=py_0
  - python-fmask=0.5.4=py37hfa6e2cd_1
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywin32=227=py37hfa6e2cd_0
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37h8055547_0
  - pyzmq=19.0.0=py37h8c16cda_1
  - qt=5.12.5=h7ef1ec2_0
  - qtconsole=4.7.2=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rios=1.4.10=py_0
  - rsgislib=4.0.6=py37h85fde98_1
  - scikit-learn=0.22.2.post1=py37h7208079_0
  - scipy=1.4.1=py37h9439919_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - sixs=1.1.2=h5b33459_1
  - sqlite=3.30.1=hfa6e2cd_0
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.0=hffbbd95_2
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - tuiview=1.2.6=py37hf509c0d_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_1
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.2=hfa6e2cd_1
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=hd8a0e53_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Users\santinel\AppData\Local\Continuum\anaconda2\envs\lsnew

